# This workflow's name, as it will appear on the Actions tab in GitHub.
name: Build and Release Electron App

# This specifies the event that triggers the workflow.
# It will run on every push to the 'app' branch.
on:
  push:
    branches:
      - app

# A workflow is composed of one or more jobs that can run sequentially or in parallel.
jobs:
  # The name of the job.
  build:
    # This specifies the type of machine to run the job on.
    runs-on: ubuntu-latest

    # The steps that make up this job.
    steps:
      # Step 1: Checks out your repository's code under $GITHUB_WORKSPACE.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up a Node.js environment.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a long-term support (LTS) version

      # Step 3: Installs all project dependencies.
      - name: Install dependencies
        run: npm install

      # Step 4: Runs the Electron build command.
      - name: Build and package the Electron app
        run: npm run build

      # Step 5: Creates a new GitHub Release and uploads the build files.
      # This step will create a new release with a unique name based on the commit.
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/app')
        with:
          # The name of the release. This will be visible on your repository's Releases page.
          name: App Build (${{ github.sha }})
          # Sets a tag for this release. Using the commit hash ensures it's unique.
          tag_name: build-${{ github.sha }}
          # The body of the release, which can contain a message.
          body: This is an automated build from the 'app' branch.
          # The files to upload from the 'dist' folder created by electron-builder.
          # The '**' is a wildcard to grab all files inside that folder.
          files: |
            dist/*
        env:
          # This provides the necessary token for the action to create the release.
          # This token is automatically provided by GitHub; you don't need to create it.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

